// 1.2.3 census-gap-fill (real_body,on_disk=false) | _<codexmate_lib::core::voice::llm::_::<impl serde_core::de::Deserialize for codexmate_lib::core::voice::llm::ChatMessage>::deserialize::__Visitor as serde_core::de::Visitor>::expecting::hbd5205eaf97f2678 @ 0x1006abb20 | full-body via IDA Python(IDA decompiler.decompile direct write)
__int64 __fastcall _$LT$codexmate_lib..core..voice..llm.._..$LT$impl$u20$serde_core..de..Deserialize$u20$for$u20$codexmate_lib..core..voice..llm..ChatMessage$GT$..deserialize..__Visitor$u20$as$u20$serde_core..de..Visitor$GT$::expecting::hbd5205eaf97f2678(
        __int64 a1,
        __int64 a2)
{
  return _$LT$core..fmt..Formatter$u20$as$u20$core..fmt..Write$GT$::write_str::h432a61b2c1499beb(
           a2,
           "struct ChatMessagescopestartedAtfinishedAttokenstruct AccountRefreshReport with 8 elementsstruct McpServerListPayload with 4 elementsattemptedsucceededstruct RefreshChannelReport with 4 elementsrelativePathdirectoryPathskillFilePathupdatedAtstruct InstalledSkillSummary with 8 elementsusageStatususageLastErrorstruct ApiConnectivityPayload with 2 elementsstruct ClaudeResponsethreshold5hPercentthresholdWeeklyPercentserviceStateserviceLabelstruct AutoSwitchStatusPayload with 5 elementsstruct StoredLlmConfigvalidatorstruct CachedRolloutEntrystruct UsageAnalyticsIndexstruct ClaudeContentBlockstruct UsageAnalyticsPayloadstruct UsageAnalyticsPayload with 3 elementsstruct ChatCompletionResponsestruct PerModeShortcutstruct VoiceRuntimeFilestruct variant VoiceSidecarEvent::Statestruct variant VoiceSidecarEvent::Errorstruct variant VoiceSidecarEvent::Readystruct variant VoiceSidecarEvent::Transcriptstruct variant VoiceSidecarEvent::AudioLevelstruct variant VoiceSidecarEvent::PermissionssessionIdisFinalemotionmicrophonespeechRecognitionlevelstruct variant VoiceSidecarEvent::Error with 3 elementsstruct variant VoiceSidecarEvent::Permissions with 2 elementsstruct variant VoiceSidecarEvent::Transcript with 5 elementsstruct variant VoiceSidecarEvent::AudioLevel with 2 elementsstruct variant VoiceSidecarEvent::State with 2 elements",
           18);
}
