// __ZN13codexmate_lib4core5relay12codex_writer19render_bottom_block @ 0x101469910
// 1.2.3 NEW-delta | codexmate_lib::core::relay::codex_writer::render_bottom_block | vs 1.2.2 新增(IDA函数枚举diff, 名↔地址一致)
__int64 __fastcall codexmate_lib::core::relay::codex_writer::render_bottom_block::hfe725bfceb75b183(
        _QWORD *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6)
{
  __int64 v9; // r9
  __int64 v10; // rcx
  size_t v11; // r12
  size_t v12; // rax
  __int64 v13; // rsi
  size_t v14; // r12
  size_t v15; // r12
  size_t v16; // rax
  __int64 v17; // rax
  __int64 v18; // r15
  int v19; // ecx
  char v20; // dl
  char v21; // si
  char v22; // di
  __int64 v23; // r15
  int v24; // esi
  int v25; // edx
  size_t v26; // r14
  __int64 v27; // r9
  __int64 v28; // r14
  void *v29; // r15
  size_t v30; // rbx
  __int64 v31; // r13
  size_t v32; // r12
  __int64 v33; // r9
  size_t v34; // r12
  size_t v35; // rdx
  size_t v36; // r12
  __int64 v37; // r9
  int **v38; // rbx
  void *v39; // r14
  size_t v40; // r15
  __int64 v41; // r9
  size_t v42; // r12
  __int64 v43; // r13
  char *v44; // rbx
  size_t v45; // r12
  size_t v46; // r12
  size_t v47; // r12
  size_t v48; // r14
  __int64 v49; // r9
  size_t v50; // r14
  __int64 v51; // r15
  size_t v52; // rax
  _QWORD *v53; // r12
  __int64 v54; // rbx
  size_t v55; // r14
  __int64 v56; // r9
  size_t v57; // r14
  __int64 result; // rax
  _QWORD v59[2]; // [rsp+8h] [rbp-C8h] BYREF
  _QWORD v60[2]; // [rsp+18h] [rbp-B8h] BYREF
  _QWORD *v61; // [rsp+28h] [rbp-A8h]
  size_t v62; // [rsp+30h] [rbp-A0h]
  int **v63; // [rsp+38h] [rbp-98h] BYREF
  void *v64; // [rsp+40h] [rbp-90h]
  size_t v65; // [rsp+48h] [rbp-88h]
  void *v66; // [rsp+50h] [rbp-80h]
  __int64 v67; // [rsp+58h] [rbp-78h]
  __int64 v68; // [rsp+60h] [rbp-70h] BYREF
  void *__src; // [rsp+68h] [rbp-68h]
  size_t __n; // [rsp+70h] [rbp-60h]
  __int64 v71; // [rsp+78h] [rbp-58h] BYREF
  void *v72; // [rsp+80h] [rbp-50h]
  size_t v73; // [rsp+88h] [rbp-48h]
  __int64 v74; // [rsp+90h] [rbp-40h] BYREF
  __int64 v75; // [rsp+98h] [rbp-38h]
  size_t v76; // [rsp+A0h] [rbp-30h]

  v74 = 0; /*0x10146992d*/
  v75 = 1; /*0x101469935*/
  v76 = 0; /*0x10146993d*/
  alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, 0, 55, 1, 1, a6); /*0x10146995b*/
  v10 = v75; /*0x101469960*/
  v11 = v76; /*0x101469964*/
  *(_QWORD *)(v75 + v76 + 47) = 0x29594C4C41554E41LL; /*0x101469972*/
  qmemcpy((void *)(v10 + v11), "# >>> aimami-relay managed start (DO NOT EDIT MA", 48); /*0x1014699cc*/
  v12 = v11 + 55; /*0x1014699d0*/
  v76 = v11 + 55; /*0x1014699d5*/
  v13 = v74; /*0x1014699d9*/
  if ( v74 == v11 + 55 ) /*0x1014699e0*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v11 + 55, 1, 1, 1, v9); /*0x101469f85*/
    v12 = v76; /*0x101469f8a*/
    v13 = v74; /*0x101469f8e*/
    v10 = v75; /*0x101469f92*/
  }
  *(_BYTE *)(v10 + v12) = 10; /*0x1014699e6*/
  v14 = v11 + 56; /*0x1014699ea*/
  v76 = v14; /*0x1014699ee*/
  if ( v13 - v14 <= 0x2B ) /*0x1014699fc*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v14, 44, 1, 1, v9); /*0x101469fb2*/
    v14 = v76; /*0x101469fb7*/
    v13 = v74; /*0x101469fbb*/
    v10 = v75; /*0x101469fbf*/
  }
  *(_QWORD *)(v10 + v14 + 32) = 0x9F8AE58B9EE5A1A8LL; /*0x101469a0c*/
  *(_QWORD *)(v10 + v14 + 24) = 0xE6ACBDE8ADB8E420LL; /*0x101469a1b*/
  *(_QWORD *)(v10 + v14 + 16) = 0xB7C220694D614D69LL; /*0x101469a2a*/
  qmemcpy((void *)(v10 + v14), "# Generated by A", 16); /*0x101469a48*/
  *(_DWORD *)(v10 + v14 + 40) = 180192232; /*0x101469a4c*/
  v15 = v14 + 44; /*0x101469a55*/
  v76 = v15; /*0x101469a59*/
  if ( v13 - v15 <= 0x3A ) /*0x101469a67*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v15, 59, 1, 1, v9); /*0x101469fdf*/
    v15 = v76; /*0x101469fe4*/
    v13 = v74; /*0x101469fe8*/
    v10 = v75; /*0x101469fec*/
  }
  *(_QWORD *)(v10 + v15 + 48) = 0xE896BCE7A88AE58BLL; /*0x101469a77*/
  *(_QWORD *)(v10 + v15 + 40) = 0x89E681A6E88DB8E4LL; /*0x101469a86*/
  *(_QWORD *)(v10 + v15 + 32) = 0x8CBCEFA29DE9B5A1LL; /*0x101469a95*/
  *(_QWORD *)(v10 + v15 + 24) = 0xE9A894E794BAE520LL; /*0x101469aa4*/
  *(_QWORD *)(v10 + v15 + 16) = 0x694D614D69412087LL; /*0x101469ab3*/
  *(_QWORD *)(v10 + v15 + 8) = 0xBFE89A80E9B7AFE8LL; /*0x101469ac2*/
  *(_QWORD *)(v10 + v15) = 0xB994E6AEBFE42023LL; /*0x101469ad1*/
  *(_DWORD *)(v10 + v15 + 55) = 177323752; /*0x101469ad5*/
  v16 = v15 + 59; /*0x101469ade*/
  v76 = v15 + 59; /*0x101469ae3*/
  if ( v13 == v15 + 59 ) /*0x101469aea*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v13, 1, 1, 1, v9); /*0x10146a009*/
    v10 = v75; /*0x10146a00e*/
    v16 = v76; /*0x10146a012*/
  }
  *(_BYTE *)(v10 + v16) = 10; /*0x101469af0*/
  v76 = v15 + 60; /*0x101469af8*/
  while ( 1 ) /*0x101469b0b*/
  {
    v17 = a3; /*0x101469b0b*/
    if ( !a3 ) /*0x101469b11*/
      break; /*0x101469b11*/
    v18 = a2 + a3; /*0x101469b13*/
    v19 = *(char *)(a2 + v17 - 1); /*0x101469b17*/
    if ( v19 >= 0 ) /*0x101469b1e*/
    {
      a3 = v17 - 1; /*0x101469b03*/
      if ( v19 != 47 ) /*0x101469b09*/
        break; /*0x101469b09*/
    }
    else
    {
      v20 = *(_BYTE *)(v18 - 2); /*0x101469b20*/
      if ( v20 >= -64 ) /*0x101469b28*/
      {
        v23 = v18 - 2; /*0x101469b4b*/
        v25 = v20 & 0x1F; /*0x101469b4f*/
      }
      else
      {
        v21 = *(_BYTE *)(v18 - 3); /*0x101469b2a*/
        if ( v21 >= -64 ) /*0x101469b33*/
        {
          v23 = v18 - 3; /*0x101469b54*/
          v24 = v21 & 0xF; /*0x101469b58*/
        }
        else
        {
          v22 = *(_BYTE *)(v18 - 4); /*0x101469b35*/
          v23 = v18 - 4; /*0x101469b3a*/
          v24 = ((v22 & 7) << 6) | v21 & 0x3F; /*0x101469b47*/
        }
        v25 = (v24 << 6) | v20 & 0x3F; /*0x101469b61*/
      }
      a3 = v23 - a2; /*0x101469b6b*/
      if ( ((v25 << 6) | v19 & 0x3F) != 0x2F ) /*0x101469b71*/
        break; /*0x101469b71*/
    }
  }
  v60[0] = a2; /*0x101469b73*/
  v60[1] = v17; /*0x101469b7a*/
  v63 = (int **)v60; /*0x101469b88*/
  v64 = _$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$::fmt::hc155efd4ae9c9554; /*0x101469b96*/
  alloc::fmt::format::format_inner::h3c16c74008a310d4(&v68, &unk_1017BA4FB, &v63); /*0x101469baf*/
  v61 = a1; /*0x101469bb4*/
  v67 = v68; /*0x101469bbf*/
  v66 = __src; /*0x101469bc7*/
  v26 = __n; /*0x101469bcb*/
  v71 = 0; /*0x101469bcf*/
  v72 = (void *)1; /*0x101469bd7*/
  v73 = 0; /*0x101469bdf*/
  v63 = &anon_3ce6d1417794db0febde534c64082f90_166; /*0x101469bee*/
  v64 = _$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$::fmt::hc155efd4ae9c9554; /*0x101469bf5*/
  alloc::fmt::format::format_inner::h3c16c74008a310d4(&v68, &unk_1017C51E7, &v63); /*0x101469c0e*/
  v62 = v26; /*0x101469c13*/
  v28 = v68; /*0x101469c1a*/
  v29 = __src; /*0x101469c1e*/
  v30 = __n; /*0x101469c22*/
  if ( __n ) /*0x101469c29*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, 0, __n, 1, 1, v27); /*0x10146a02f*/
    v31 = (__int64)v72; /*0x10146a034*/
    v32 = v73; /*0x10146a038*/
  }
  else
  {
    v31 = 1; /*0x101469c2f*/
    v32 = 0; /*0x101469c35*/
  }
  memcpy((void *)(v31 + v32), v29, v30); /*0x101469c43*/
  v34 = v30 + v32; /*0x101469c48*/
  v73 = v34; /*0x101469c4b*/
  if ( v28 ) /*0x101469c52*/
    _RNvCs1Y7DaGC1cwg_7___rustc14___rust_dealloc(v29, v28, 1); /*0x101469c5f*/
  if ( v71 - v34 <= 0x1C ) /*0x101469c6f*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, v34, 29, 1, 1, v33); /*0x10146a058*/
    v35 = v62; /*0x10146a05d*/
    v31 = (__int64)v72; /*0x10146a064*/
    v34 = v73; /*0x10146a068*/
  }
  else
  {
    v35 = v62; /*0x101469c75*/
  }
  *(_QWORD *)(v31 + v34 + 21) = 0xA22B194E7AFB7E8LL; /*0x101469c86*/
  *(_QWORD *)(v31 + v34 + 16) = 0xAFB7E8BD83E8BA99LL; /*0x101469c95*/
  *(_QWORD *)(v31 + v34 + 8) = 0xE620694D614D6941LL; /*0x101469ca4*/
  *(_QWORD *)(v31 + v34) = 0x22203D20656D616ELL; /*0x101469cb3*/
  v36 = v34 + 29; /*0x101469cb8*/
  v73 = v36; /*0x101469cbc*/
  codexmate_lib::core::relay::codex_writer::escape_toml::ha83802857195c924(&v68, v66, v35); /*0x101469ccb*/
  v59[0] = &v68; /*0x101469cd0*/
  v59[1] = _$LT$alloc..string..String$u20$as$u20$core..fmt..Display$GT$::fmt::h31d6615ee8f7bc50; /*0x101469cde*/
  alloc::fmt::format::format_inner::h3c16c74008a310d4(&v63, &unk_1017C51FE, v59); /*0x101469cfa*/
  if ( v68 ) /*0x101469d06*/
    _RNvCs1Y7DaGC1cwg_7___rustc14___rust_dealloc(__src, v68, 1); /*0x101469d11*/
  v38 = v63; /*0x101469d16*/
  v39 = v64; /*0x101469d1d*/
  v40 = v65; /*0x101469d24*/
  if ( v65 > v71 - v36 ) /*0x101469d35*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, v36, v65, 1, 1, v37); /*0x10146a086*/
    v31 = (__int64)v72; /*0x10146a08b*/
    v36 = v73; /*0x10146a08f*/
  }
  memcpy((void *)(v36 + v31), v39, v40); /*0x101469d47*/
  v42 = v40 + v36; /*0x101469d4c*/
  v73 = v42; /*0x101469d4f*/
  if ( v38 ) /*0x101469d56*/
    _RNvCs1Y7DaGC1cwg_7___rustc14___rust_dealloc(v39, v38, 1); /*0x101469d63*/
  v43 = v71; /*0x101469d68*/
  if ( v71 - v42 <= 0x16 ) /*0x101469d76*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, v42, 23, 1, 1, v41); /*0x10146a0af*/
    v43 = v71; /*0x10146a0b4*/
    v42 = v73; /*0x10146a0b8*/
  }
  v44 = (char *)v72; /*0x101469d7c*/
  *(_QWORD *)((char *)v72 + v42 + 15) = 0xA227365736E6F70LL; /*0x101469d8a*/
  qmemcpy(&v44[v42], "wire_api = \"resp", 16); /*0x101469da8*/
  v45 = v42 + 23; /*0x101469dac*/
  v73 = v45; /*0x101469db0*/
  if ( v43 - v45 <= 0x1B ) /*0x101469dbe*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, v45, 28, 1, 1, v41); /*0x10146a0d8*/
    v45 = v73; /*0x10146a0dd*/
    v43 = v71; /*0x10146a0e1*/
    v44 = (char *)v72; /*0x10146a0e5*/
  }
  qmemcpy(&v44[v45], "requires_openai_auth = true\n", 28); /*0x101469dec*/
  v46 = v45 + 28; /*0x101469df9*/
  v73 = v46; /*0x101469dfd*/
  if ( v43 - v46 <= 0x1B ) /*0x101469e0b*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v71, v46, 28, 1, 1, v41); /*0x10146a105*/
    v46 = v73; /*0x10146a10a*/
    v43 = v71; /*0x10146a10e*/
    v44 = (char *)v72; /*0x10146a112*/
  }
  qmemcpy(&v44[v46], "supports_websockets = false\n", 28); /*0x101469e39*/
  v47 = v46 + 28; /*0x101469e46*/
  if ( v67 ) /*0x101469e51*/
    _RNvCs1Y7DaGC1cwg_7___rustc14___rust_dealloc(v66, v67, 1); /*0x101469e5c*/
  v48 = v76; /*0x101469e65*/
  if ( v47 > v74 - v76 ) /*0x101469e6f*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v76, v47, 1, 1, v41); /*0x10146a130*/
    v48 = v76; /*0x10146a135*/
  }
  memcpy((void *)(v48 + v75), v44, v47); /*0x101469e82*/
  v50 = v47 + v48; /*0x101469e87*/
  v76 = v50; /*0x101469e8a*/
  if ( v43 ) /*0x101469e91*/
    _RNvCs1Y7DaGC1cwg_7___rustc14___rust_dealloc(v44, v43, 1); /*0x101469e9e*/
  v51 = v74; /*0x101469ea3*/
  v52 = v50; /*0x101469ea7*/
  v53 = v61; /*0x101469ead*/
  if ( v74 == v50 ) /*0x101469eb4*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v50, 1, 1, 1, v49); /*0x10146a155*/
    v51 = v74; /*0x10146a15a*/
    v52 = v76; /*0x10146a15e*/
  }
  v54 = v75; /*0x101469eba*/
  *(_BYTE *)(v75 + v52) = 10; /*0x101469ebe*/
  v55 = v50 + 1; /*0x101469ec2*/
  v76 = v55; /*0x101469ec5*/
  if ( v51 - v55 <= 0x55 ) /*0x101469ed3*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v55, 86, 1, 1, v49); /*0x10146a17e*/
    v55 = v76; /*0x10146a183*/
    v51 = v74; /*0x10146a187*/
    v54 = v75; /*0x10146a18b*/
  }
  memcpy((void *)(v54 + v55), &unk_101673A9B, 0x56u); /*0x101469ee9*/
  v57 = v55 + 86; /*0x101469eee*/
  v76 = v57; /*0x101469ef2*/
  if ( v51 - v57 <= 0x1D ) /*0x101469efd*/
  {
    alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::h9724c97fda9adefb(&v74, v57, 30, 1, 1, v56); /*0x10146a1ab*/
    v54 = v75; /*0x10146a1b0*/
    v57 = v76; /*0x10146a1b4*/
  }
  qmemcpy((void *)(v54 + v57), "# <<< aimami-relay managed end", 30); /*0x101469f3a*/
  v76 = v57 + 30; /*0x101469f42*/
  v53[2] = v57 + 30; /*0x101469f46*/
  result = v74; /*0x101469f4b*/
  v53[1] = v75; /*0x101469f53*/
  *v53 = result; /*0x101469f58*/
  return result; /*0x101469f5c*/
}